.TH STMELTDOWN 6 "" "SuperTux Meltdown" "Games"

.SH NAME
stmeltdown \- Attempt to refactor SuperTux

.SH SYNOPSIS
.B stmeltdown
.RI [options]

.SH DESCRIPTION
SuperTux Meltdown is an attempt at remaking SuperTux with increased efforts put
into code quality, planification, retrocompatibility, use case consideration and
cross-platform usability.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-d, \-\-data PATH
Change the data folder
.TP
.B \-h, \-\-help
Show this help text and exit
.TP
.B \-t, \-\-test
Run the test suite
.TP
.B \-v, \-\-version
Show SuperTux version and quit
